

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tilt-project_backend
    volumes:
      - ./utils:/app/utils
      - ./setup:/app/setup
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    # inspect dir and all
    # command: ls /app
    command: ["sh", "-c", "chmod +x /app/setup/setup.sh && /app/setup/setup.sh && npm start"]
  
  frontend:
    # no need of this 'build' part as we are not creating our own customised image for front end 
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend
