version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tilt-project_backend
    volumes:
      - ./utils:/app/utils
      - ./setup:/app/setup
    ports:
      - "3000:3000"
    # incpect dir and all
    # command: ls -R /app/utils
    command: ["sh", "-c", "chmod +x /app/setup/setup.sh && /app/setup/setup.sh && npm start"]
