load('ext://restart_process', 'docker_build_with_restart')

docker_compose('../docker-compose.yml')

docker_build(
  'tilt-project_backend',
  '..',
  dockerfile='Dockerfile',
  live_update = [
    sync('backend', '/app/backend'),
    sync('../utils', '/app/utils'),
    # run('chmod +x /app/setup/setup.sh && /app/setup/setup.sh'),
    restart_container()
  ]
)

# No need of this part anymore because we are not creating an image for frontend folder as we not using its docker file 

# docker_build(
#     'tilt-project_frontend',
#     '.',
#     dockerfile='-',
#     live_update=[
#         sync('../frontend', '/usr/share/nginx/html'),
#         restart_container()
#     ]
# )